default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: login_development

test:
  <<: *default
  database: login_test

production:
  <<: *default
  database: login_production
  username: login
  password: <%= ENV["LOGIN_DATABASE_PASSWORD"] %>